import { Thread, Message } from './types';

export const DEMO_THREADS: Thread[] = [
  {
    id: 'demo-1',
    gmail_thread_id: 'thread_demo_001',
    subject: 'Besloten verjaardag 50 jaar - april 2025',
    contact_name: 'Marianne de Vries',
    contact_email: 'marianne.devries@gmail.com',
    last_message_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'TO_ANSWER',
    has_unread: true,
    assigned_to: null,
    extracted_summary: 'Marianne wil haar 50e verjaardag vieren met 30 personen op zaterdag 12 april. Vraagt naar beschikbaarheid, driegangenmenu en mogelijkheid voor een verrassingstaart. Ook optie gevraagd voor 19 april als alternatief.',
    extracted_appointment_json: {
      hasAppointment: false,
      appointment: { date: '2025-04-12', time: '19:00', partySize: 30, occasion: 'verjaardag', notes: 'Diner met driegangenmenu' },
      statusHint: 'TO_ANSWER',
      confidence: 0.7,
      keyEvidence: ['30 personen voor mijn 50e verjaardag', 'zaterdag 12 april als eerste keuze'],
    },
    conversion: false,
    notes: null,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-2',
    gmail_thread_id: 'thread_demo_002',
    subject: 'Borrel afsluiting project - De Heeren',
    contact_name: 'Thomas Bakker',
    contact_email: 'thomas.bakker@acme.nl',
    last_message_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'ANSWERED',
    has_unread: false,
    assigned_to: null,
    extracted_summary: 'Bedrijfsborrel voor ~25 personen, vrijdag eind van de middag. Café heeft gereageerd met beschikbaarheid, wacht op bevestiging.',
    extracted_appointment_json: {
      hasAppointment: false,
      appointment: { date: null, time: '17:00', partySize: 25, occasion: 'borrel', notes: 'Borrel met bitterballen' },
      statusHint: 'ANSWERED',
      confidence: 0.6,
      keyEvidence: ['vrijdag eind van de middag', 'ongeveer 25 collega\'s'],
    },
    conversion: false,
    notes: 'Wacht op goedkeuring budget bij opdrachtgever',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-3',
    gmail_thread_id: 'thread_demo_003',
    subject: 'Privé diner huwelijksjubileum',
    contact_name: 'Familie Janssen',
    contact_email: 'h.janssen@hotmail.com',
    last_message_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'GO',
    has_unread: false,
    assigned_to: null,
    extracted_summary: 'Huwelijksjubileum (25 jaar) voor 15 personen. Afspraak gemaakt voor 22 maart om 18:30. Aanbetaling ontvangen.',
    extracted_appointment_json: {
      hasAppointment: true,
      appointment: { date: '2025-03-22', time: '18:30', partySize: 15, occasion: 'diner', notes: '25 jarig huwelijksjubileum, speciale taartopmaak gevraagd' },
      statusHint: 'GO',
      confidence: 0.98,
      keyEvidence: ['staat in de agenda voor 22 maart 18:30', 'aanbetaling van €150 ontvangen'],
    },
    conversion: true,
    notes: 'Aanbetaling €150 ontvangen op 15 jan',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-4',
    gmail_thread_id: 'thread_demo_004',
    subject: 'Kinderfeestje - 8e verjaardag Emma',
    contact_name: 'Sandra Pietersen',
    contact_email: 'sandra.pietersen@gmail.com',
    last_message_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'NO_GO',
    has_unread: false,
    assigned_to: null,
    extracted_summary: 'Kinderfeestje geannuleerd. Gaat niet door vanwege verhuizing naar andere stad.',
    extracted_appointment_json: {
      hasAppointment: false,
      appointment: { date: null, time: null, partySize: 12, occasion: 'verjaardag', notes: null },
      statusHint: 'NO_GO',
      confidence: 0.95,
      keyEvidence: ['we gaan toch niet door', 'verhuizen naar Utrecht'],
    },
    conversion: false,
    notes: null,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-5',
    gmail_thread_id: 'thread_demo_005',
    subject: 'Receptie opening nieuwe zaak',
    contact_name: 'Kevin Smit',
    contact_email: 'kevin@smitdesign.nl',
    last_message_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    status: 'TO_ANSWER',
    has_unread: true,
    assigned_to: null,
    extracted_summary: 'Opening nieuwe designstudio, receptie voor ~60 personen op een vrijdagavond. Vraagt naar capaciteit en catering.',
    extracted_appointment_json: {
      hasAppointment: false,
      appointment: { date: null, time: '19:00', partySize: 60, occasion: 'receptie', notes: 'Canapés en drankjes' },
      statusHint: 'TO_ANSWER',
      confidence: 0.65,
      keyEvidence: ['opening van mijn studio', '60 mensen verwacht', 'vrijdagavond in mei'],
    },
    conversion: false,
    notes: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-6',
    gmail_thread_id: 'thread_demo_006',
    subject: 'Trouwreceptie - Juli 2025',
    contact_name: 'Lars & Eva Vermeer',
    contact_email: 'larsvermeer@gmail.com',
    last_message_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'GO',
    has_unread: false,
    assigned_to: null,
    extracted_summary: 'Trouwreceptie voor 80 personen op 5 juli 2025 om 15:00. Volledig uitgedacht, catering bevestigd.',
    extracted_appointment_json: {
      hasAppointment: true,
      appointment: { date: '2025-07-05', time: '15:00', partySize: 80, occasion: 'trouwerij', notes: 'Walking dinner, open bar 4 uur' },
      statusHint: 'GO',
      confidence: 0.99,
      keyEvidence: ['trouwreceptie 5 juli bevestigd', 'factuur verstuurd', '80 gasten definitief'],
    },
    conversion: true,
    notes: 'Factuur €2.400 verstuurd, helft betaald',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_MESSAGES: Record<string, Message[]> = {
  'demo-1': [
    {
      id: 'msg-1-1',
      thread_id: 'demo-1',
      gmail_message_id: 'gmail_msg_1_1',
      from_name: 'Marianne de Vries',
      from_email: 'marianne.devries@gmail.com',
      to_emails: ['info@cafedeheeren.nl'],
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      snippet: 'Goedemiddag, ik wil graag mijn 50e verjaardag vieren bij jullie...',
      body_plain: 'Goedemiddag,\n\nIk wil graag mijn 50e verjaardag vieren bij jullie restaurant. We zijn met 30 personen en ik dacht aan zaterdag 12 april als eerste keuze.\n\nKunnen jullie aangeven of dit beschikbaar is en wat de mogelijkheden zijn voor een driegangenmenu?\n\nMet vriendelijke groet,\nMarianne de Vries',
      body_html: null,
      direction: 'INBOUND',
    },
    {
      id: 'msg-1-2',
      thread_id: 'demo-1',
      gmail_message_id: 'gmail_msg_1_2',
      from_name: 'Café De Heeren',
      from_email: 'info@cafedeheeren.nl',
      to_emails: ['marianne.devries@gmail.com'],
      date: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
      snippet: 'Beste Marianne, hartelijk dank voor uw interesse...',
      body_plain: 'Beste Marianne,\n\nHartelijk dank voor uw interesse in Café De Heeren voor uw 50e verjaardag!\n\nZaterdag 12 april hebben we nog beschikbaarheid voor een besloten feest van 30 personen. We bieden inderdaad driegangenmenu\'s aan vanaf €45 per persoon.\n\nKunt u ons meer vertellen over uw wensen qua tijd en eventueel een thema?\n\nMet vriendelijke groet,\nTeam Café De Heeren',
      body_html: null,
      direction: 'OUTBOUND',
    },
    {
      id: 'msg-1-3',
      thread_id: 'demo-1',
      gmail_message_id: 'gmail_msg_1_3',
      from_name: 'Marianne de Vries',
      from_email: 'marianne.devries@gmail.com',
      to_emails: ['info@cafedeheeren.nl'],
      date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      snippet: 'Dank voor de snelle reactie! We dachten aan een aanvang om 18:00...',
      body_plain: 'Dank voor de snelle reactie!\n\nWe dachten aan een aanvang om 18:00 uur. Geen speciaal thema, wel zou ik graag een kleine verrassingstaart willen. Is dat mogelijk?\n\nKan ik ook een optie nemen voor de 19e april mocht de 12e toch niet uitkomen?\n\nMet vriendelijke groet,\nMarianne',
      body_html: null,
      direction: 'INBOUND',
    },
  ],
  'demo-3': [
    {
      id: 'msg-3-1',
      thread_id: 'demo-3',
      gmail_message_id: 'gmail_msg_3_1',
      from_name: 'Familie Janssen',
      from_email: 'h.janssen@hotmail.com',
      to_emails: ['info@cafedeheeren.nl'],
      date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      snippet: 'Wij vieren ons 25-jarig huwelijksjubileum...',
      body_plain: 'Goedemorgen,\n\nWij vieren ons 25-jarig huwelijksjubileum en willen dat graag doen bij Café De Heeren. We zijn met 15 personen.\n\nKan dat op zaterdag 22 maart om half zeven?\n\nMet vriendelijke groet,\nH. Janssen',
      body_html: null,
      direction: 'INBOUND',
    },
    {
      id: 'msg-3-2',
      thread_id: 'demo-3',
      gmail_message_id: 'gmail_msg_3_2',
      from_name: 'Café De Heeren',
      from_email: 'info@cafedeheeren.nl',
      to_emails: ['h.janssen@hotmail.com'],
      date: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
      snippet: 'Gefeliciteerd alvast met uw jubileum! Zaterdag 22 maart staat in de agenda...',
      body_plain: 'Gefeliciteerd alvast met uw jubileum!\n\nZaterdag 22 maart om 18:30 staat in de agenda voor 15 personen. Wij sturen u nog een bevestiging met het verzoek om €150 aanbetaling.\n\nMet vriendelijke groet,\nTeam Café De Heeren',
      body_html: null,
      direction: 'OUTBOUND',
    },
    {
      id: 'msg-3-3',
      thread_id: 'demo-3',
      gmail_message_id: 'gmail_msg_3_3',
      from_name: 'Familie Janssen',
      from_email: 'h.janssen@hotmail.com',
      to_emails: ['info@cafedeheeren.nl'],
      date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      snippet: 'De aanbetaling van €150 heb ik overgemaakt...',
      body_plain: 'Goedemiddag,\n\nDe aanbetaling van €150 heb ik zojuist overgemaakt. Wij kijken er naar uit!\n\nMet vriendelijke groet,\nH. Janssen',
      body_html: null,
      direction: 'INBOUND',
    },
  ],
};
