import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { getGmailClient, extractEmailBody, parseEmailAddress, CAFE_EMAIL, GMAIL_LABEL } from '@/lib/gmail';
import { supabaseAdmin } from '@/lib/supabase';
import { extractEventDataFromEmail } from '@/lib/anthropic';
import { ThreadStatus, PrivateEventRequest } from '@/lib/types';

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.accessToken) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const gmail = getGmailClient(session.accessToken);

    // Get label ID for "Besloten feestje"
    const labelsRes = await gmail.users.labels.list({ userId: 'me' });
    const labels = labelsRes.data.labels || [];
    const targetLabel = labels.find(l => l.name?.toLowerCase() === GMAIL_LABEL.toLowerCase());

    if (!targetLabel?.id) {
      return NextResponse.json({ error: `Label "${GMAIL_LABEL}" not found` }, { status: 404 });
    }

    // Fetch threads with this label
    const threadsRes = await gmail.users.threads.list({
      userId: 'me',
      labelIds: [targetLabel.id],
      maxResults: 100,
    });

    const gmailThreads = threadsRes.data.threads || [];
    let synced = 0;

    for (const gmailThread of gmailThreads) {
      // Check if already synced (deduplication)
      const { data: existing } = await supabaseAdmin
        .from('private_event_requests')
        .select('id')
        .eq('gmail_thread_id', gmailThread.id!)
        .single();

      if (existing) {
        continue; // Skip already synced threads
      }

      const threadDetail = await gmail.users.threads.get({
        userId: 'me',
        id: gmailThread.id!,
        format: 'full',
      });

      const messages = threadDetail.data.messages || [];
      if (messages.length === 0) continue;

      // Parse messages
      const parsedMessages = messages.map(msg => {
        const headers = msg.payload?.headers || [];
        const getHeader = (name: string) => headers.find(h => h.name?.toLowerCase() === name.toLowerCase())?.value || '';

        const fromHeader = getHeader('from');
        const { name: fromName, email: fromEmail } = parseEmailAddress(fromHeader);
        const toHeader = getHeader('to');
        const toEmails = toHeader.split(',').map(e => parseEmailAddress(e.trim()).email);
        const date = new Date(parseInt(msg.internalDate || '0')).toISOString();
        const { plain, html } = extractEmailBody(msg.payload);

        return {
          gmail_message_id: msg.id!,
          from_name: fromName,
          from_email: fromEmail,
          to_emails: toEmails,
          date,
          snippet: msg.snippet || '',
          body_plain: plain,
          body_html: html,
          direction: (fromEmail.toLowerCase() === CAFE_EMAIL.toLowerCase() ? 'OUTBOUND' : 'INBOUND') as 'INBOUND' | 'OUTBOUND',
        };
      });

      // Get sender from first INBOUND message
      const firstInbound = parsedMessages.find(m => m.direction === 'INBOUND');
      if (!firstInbound) continue; // Skip if no inbound message

      const senderEmail = firstInbound.from_email;
      const senderName = firstInbound.from_name;
      const emailBody = firstInbound.body_plain || firstInbound.snippet || '';

      // AI extraction
      let extractedData = {
        senderName: senderName,
        occasionType: null as string | null,
        eventDate: null as string | null,
        startTime: null as string | null,
        endTime: null as string | null,
        guestCount: null as number | null,
        specialNotes: null as string | null,
        aiSummary: null as string | null,
      };

      try {
        extractedData = await extractEventDataFromEmail(emailBody);
      } catch (error) {
        console.warn('AI extraction failed, using defaults:', error);
      }

      // Create new private_event_request
      const newRequest: PrivateEventRequest = {
        id: '', // Will be generated by Supabase
        gmail_thread_id: gmailThread.id!,
        sender_name: extractedData.senderName || senderName,
        sender_email: senderEmail,
        occasion_type: extractedData.occasionType,
        event_date: extractedData.eventDate,
        start_time: extractedData.startTime,
        end_time: extractedData.endTime,
        guest_count: extractedData.guestCount,
        special_notes: extractedData.specialNotes,
        ai_summary: extractedData.aiSummary,
        status: 'TO_ANSWER' as ThreadStatus,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        archived_at: null,
      };

      // Insert new request
      const { data: created } = await supabaseAdmin
        .from('private_event_requests')
        .insert(newRequest)
        .select()
        .single();

      if (created) {
        // Insert messages
        for (const msg of parsedMessages) {
          await supabaseAdmin.from('messages').insert({
            thread_id: created.id,
            ...msg,
          });
        }
        synced++;
      }
    }

    return NextResponse.json({ success: true, synced });
  } catch (error: any) {
    console.error('Gmail sync error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
